---
- name: install PostgreSQL
  sudo: yes
  apt: name={{ item }} update_cache=true state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- name: Ensure the PostgreSQL service is running
  service: 
    name: postgresql 
    state: started 
    enabled: yes

- name: Create postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "root"
    password: "postgrespasswd"

- name: Ensure user has access to database
  become: yes
  become_user: postgres
  postgresql_privs:
    db: snailRacing
    role: root
    objs: ALL_IN_SCHEMA
    privs: ALL
