  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes

  - name: Install Python
    apt:
      name: python3
      state: present
      
  - name: Install PIP3
    apt:
      name: python3-pip
      state: present

  - name: Install PIP2
    apt:
      name: python-pip
      state: present

  - name: Install Flask
    pip:
      name: Flask
      executable: pip

  - name: Install Flask-Cors
    pip:
      name: flask-cors
      executable: pip

  - name: Install VirtualEnv
    pip:
      name: virtualenv
      executable: pip3

  - name: Core VirtualEnv Setup
    pip:
      virtualenv: "{{ core_venv }}"
      virtualenv_python: python3
      requirements: "{{ core_req }}"

  - name: Feed VirtualEnv Setup
    pip:
      virtualenv: "{{ feed_venv }}"
      virtualenv_python: python3
      requirements: "{{ feed_req }}"
