
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install Python
    apt:
      name: python
      update_cache: yes
  - name: Install PIP
    apt:
      name: pip
      update_cache: yes
  - name: Install VirtualEnv
    apt:
      name: virtualenv
      update_cache: yes
