
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes

  - name: Install Python
    apt:
      name: python3

  - name: Install PIP
    apt:
      name: python-pip

  - name: Install VirtualEnv
    apt:
      name: virtualenv
