  - name: Install NPM
    apt:
      name: npm
      state: present

  - name: Install @vue/cli
    npm:
      name: "@vue/cli"
      global: true

  - name: Install vue-resource
    npm:
      name: vue-resource
      global: true

  - name: install npm in vue
    shell: npm install
    args:
      chdir: /vagrant/snail-x-core-vue
